/**
 * Chatbot.jsx — GraphBot AI Assistant
 * =====================================
 * Floating chat bubble (bottom-right) that opens a slide-in panel.
 * Connects to POST /api/chat (Groq LLM with GST function calling).
 * Falls back to FAQ answers when backend is offline.
 */

import { useState, useRef, useEffect } from 'react';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:8001';

// ── Suggested quick-action chips ────────────────────────────────────────────
const SUGGESTIONS = [
  '📊 Show dashboard summary',
  '🚨 List CRITICAL risk invoices',
  '🏭 Which vendors are high risk?',
  '🔄 Any circular trading detected?',
  '💰 What is my ITC reversal liability?',
  '📜 Explain Section 16(2)(aa)',
  '❓ What is GSTR-2B?',
  '📋 How does IRN work?',
];

// ── Offline FAQ fallback (shown when backend is unreachable) ─────────────────
const FAQ = {
  'gstr-2b': 'GSTR-2B is the auto-populated ITC statement generated by GSTN on the 14th of each month. It reflects invoices uploaded by your suppliers in GSTR-1. Under Section 16(2)(aa), ITC is only allowed when the invoice appears in your GSTR-2B.',
  'irn': 'IRN (Invoice Reference Number) is a unique 64-character hash generated by the IRP (Invoice Registration Portal) under e-Invoicing. It\'s mandatory for B2B invoices above the e-invoicing threshold. Missing IRN = GSTN doesn\'t recognize the invoice = ITC blocked.',
  'itc': 'ITC (Input Tax Credit) is the GST paid on your purchases that you can offset against GST collected on sales. The eligibility chain: Supplier files GSTR-1 → GSTN generates your GSTR-2B → You claim ITC in GSTR-3B.',
  'section 16': 'Section 16(2)(aa) of CGST Act: ITC is admissible ONLY when the invoice appears in the recipient\'s GSTR-2B. This was inserted by Finance Act 2021 and makes GSTR-2B the eligibility gate.',
  'circular': 'Circular trading is a fraud pattern where a ring of companies pass fake invoices between each other to generate fraudulent ITC claims. GraphLedger AI detects these using graph cycle detection algorithms.',
};

function getOfflineAnswer(msg) {
  const lower = msg.toLowerCase();
  for (const [key, answer] of Object.entries(FAQ)) {
    if (lower.includes(key)) return answer;
  }
  return "I'm currently offline — the backend server isn't running. Start it with `python api.py` in the gst_engine folder, then try again.";
}

// ── Markdown renderer — handles tables, headers, bullets, bold, code ─────────
function inlineFormat(text) {
  // Split on **bold** and `code` spans
  const parts = text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
  return parts.map((p, i) => {
    if (p.startsWith('**') && p.endsWith('**')) return <strong key={i}>{p.slice(2, -2)}</strong>;
    if (p.startsWith('`') && p.endsWith('`')) return <code key={i} style={{ background: '#f0f0f0', borderRadius: 3, padding: '1px 5px', fontSize: '11px', fontFamily: 'Space Mono, monospace' }}>{p.slice(1, -1)}</code>;
    return p;
  });
}

function RenderMessage({ text }) {
  const lines = text.split('\n');
  const out = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const trim = line.trim();

    // ── Horizontal rule
    if (/^---+$/.test(trim)) { out.push(<hr key={i} style={{ border: 'none', borderTop: '1px solid #e5e7eb', margin: '8px 0' }} />); i++; continue; }

    // ── Heading ### / ##
    if (trim.startsWith('### ')) { out.push(<div key={i} style={{ fontWeight: 700, fontSize: 13, marginTop: 10, marginBottom: 4, color: '#1a1a2e' }}>{inlineFormat(trim.slice(4))}</div>); i++; continue; }
    if (trim.startsWith('## '))  { out.push(<div key={i} style={{ fontWeight: 700, fontSize: 14, marginTop: 12, marginBottom: 4, color: '#1a1a2e' }}>{inlineFormat(trim.slice(3))}</div>); i++; continue; }
    if (trim.startsWith('> '))   { out.push(<div key={i} style={{ borderLeft: '3px solid #f59e0b', paddingLeft: 10, color: '#6b7280', fontStyle: 'italic', fontSize: 12, margin: '6px 0' }}>{inlineFormat(trim.slice(2))}</div>); i++; continue; }

    // ── Markdown table: lines starting with |
    if (trim.startsWith('|')) {
      const tableLines = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        tableLines.push(lines[i].trim());
        i++;
      }
      // Skip separator rows (---|---)
      const rows = tableLines.filter(l => !/^\|[-| :]+\|$/.test(l));
      if (rows.length > 0) {
        const header = rows[0].split('|').filter(c => c !== '').map(c => c.trim());
        const body = rows.slice(1);
        out.push(
          <div key={`tbl-${i}`} style={{ overflowX: 'auto', margin: '8px 0' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr>{header.map((h, hi) => <th key={hi} style={{ padding: '5px 8px', background: '#f4f1ea', fontWeight: 600, textAlign: 'left', borderBottom: '2px solid #e5e7eb', whiteSpace: 'nowrap' }}>{inlineFormat(h)}</th>)}</tr>
              </thead>
              <tbody>
                {body.map((row, ri) => {
                  const cells = row.split('|').filter(c => c !== '').map(c => c.trim());
                  return <tr key={ri} style={{ background: ri % 2 === 0 ? '#fff' : '#fafafa' }}>
                    {cells.map((c, ci) => <td key={ci} style={{ padding: '5px 8px', borderBottom: '1px solid #f0f0f0' }}>{inlineFormat(c)}</td>)}
                  </tr>;
                })}
              </tbody>
            </table>
          </div>
        );
      }
      continue;
    }

    // ── Numbered list
    if (/^\d+\.\s/.test(trim)) {
      out.push(<div key={i} style={{ display: 'flex', gap: 6, marginBottom: 4, paddingLeft: 4 }}><span style={{ color: '#f59e0b', fontWeight: 700, minWidth: 16 }}>{trim.match(/^\d+/)[0]}.</span><span>{inlineFormat(trim.replace(/^\d+\.\s/, ''))}</span></div>);
      i++; continue;
    }

    // ── Bullet
    if (trim.startsWith('- ') || trim.startsWith('• ')) {
      const content = trim.replace(/^[-•]\s/, '');
      out.push(<div key={i} style={{ display: 'flex', gap: 6, marginBottom: 3, paddingLeft: 4 }}><span style={{ color: '#f59e0b', fontWeight: 700 }}>•</span><span>{inlineFormat(content)}</span></div>);
      i++; continue;
    }

    // ── Empty line
    if (!trim) { out.push(<div key={i} style={{ height: 6 }} />); i++; continue; }

    // ── Plain paragraph
    out.push(<div key={i} style={{ marginBottom: 3, lineHeight: 1.55 }}>{inlineFormat(trim)}</div>);
    i++;
  }

  return <div style={{ fontSize: 13 }}>{out}</div>;
}

// ── Main Chatbot component ────────────────────────────────────────────────────
export default function Chatbot() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      text: '👋 Hi! I\'m **GraphBot**, your GST compliance AI assistant.\n\nI can help you with:\n- ITC risk analysis & mismatch explanations\n- Vendor compliance queries\n- Fraud pattern detection\n- GST law explanations\n\nWhat would you like to know?',
    },
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [sessionId] = useState(() => `session_${Date.now()}`);
  const [hasUnread, setHasUnread] = useState(false);
  const bottomRef = useRef(null);
  const inputRef = useRef(null);

  // Auto-scroll to latest message
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Focus input when panel opens
  useEffect(() => {
    if (open) {
      setHasUnread(false);
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [open]);

  async function sendMessage(text) {
    const msg = text || input.trim();
    if (!msg || loading) return;

    setInput('');
    setMessages(prev => [...prev, { role: 'user', text: msg }]);
    setLoading(true);

    try {
      const res = await fetch(`${API_BASE}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: msg, session_id: sessionId }),
        signal: AbortSignal.timeout(30000),
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      const reply = data.reply || 'No response received.';

      setMessages(prev => [...prev, { role: 'assistant', text: reply }]);
      if (!open) setHasUnread(true);

    } catch {
      // Backend offline — use FAQ fallback
      const fallback = getOfflineAnswer(msg);
      setMessages(prev => [
        ...prev,
        {
          role: 'assistant',
          text: fallback,
          offline: true,
        },
      ]);
    } finally {
      setLoading(false);
    }
  }

  function handleKey(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  }

  function clearChat() {
    setMessages([{
      role: 'assistant',
      text: '🔄 Chat cleared. How can I help you?',
    }]);
    fetch(`${API_BASE}/api/chat/${sessionId}`, { method: 'DELETE' }).catch(() => {});
  }

  return (
    <>
      {/* ── Floating bubble ── */}
      <button
        className="chat-bubble"
        onClick={() => setOpen(o => !o)}
        title="GraphBot AI Assistant"
      >
        {open ? '✕' : '🤖'}
        {hasUnread && !open && <span className="chat-unread-dot" />}
      </button>

      {/* ── Chat panel ── */}
      {open && (
        <div className="chat-panel">
          {/* Header */}
          <div className="chat-header">
            <div className="chat-header-left">
              <span className="chat-avatar">🤖</span>
              <div>
                <div className="chat-header-name">GraphBot</div>
                <div className="chat-header-sub">
                  <span className="chat-online-dot" />
                  Groq · llama-3.3-70b
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button className="chat-icon-btn" onClick={clearChat} title="Clear chat">🗑</button>
              <button className="chat-icon-btn" onClick={() => setOpen(false)} title="Close">✕</button>
            </div>
          </div>

          {/* Messages */}
          <div className="chat-messages">
            {messages.map((m, i) => (
              <div key={i} className={`chat-msg chat-msg-${m.role}`}>
                {m.role === 'assistant' && (
                  <span className="chat-msg-avatar">🤖</span>
                )}
                <div className={`chat-bubble-msg ${m.role === 'user' ? 'chat-bubble-user' : 'chat-bubble-bot'} ${m.offline ? 'chat-offline' : ''}`}>
                  <RenderMessage text={m.text} />
                  {m.offline && (
                    <div className="chat-offline-badge">⚠ Backend offline — FAQ mode</div>
                  )}
                </div>
              </div>
            ))}

            {/* Typing indicator */}
            {loading && (
              <div className="chat-msg chat-msg-assistant">
                <span className="chat-msg-avatar">🤖</span>
                <div className="chat-bubble-msg chat-bubble-bot chat-typing">
                  <span /><span /><span />
                </div>
              </div>
            )}
            <div ref={bottomRef} />
          </div>

          {/* Suggestion chips — shown only if short conversation */}
          {messages.length <= 2 && (
            <div className="chat-suggestions">
              {SUGGESTIONS.slice(0, 4).map((s, i) => (
                <button
                  key={i}
                  className="chat-chip"
                  onClick={() => sendMessage(s)}
                  disabled={loading}
                >
                  {s}
                </button>
              ))}
            </div>
          )}

          {/* Input */}
          <div className="chat-input-row">
            <textarea
              ref={inputRef}
              className="chat-input"
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={handleKey}
              placeholder="Ask about ITC risk, vendors, fraud patterns..."
              rows={1}
              disabled={loading}
            />
            <button
              className="chat-send-btn"
              onClick={() => sendMessage()}
              disabled={!input.trim() || loading}
            >
              ➤
            </button>
          </div>
          <div className="chat-footer-note">
            Powered by Groq · openai/gpt-oss-120b · Live data
          </div>
        </div>
      )}
    </>
  );
}
