"""
Deliverable 1 — GST Knowledge Graph Schema
============================================
Defines the complete node/edge schema for India's GST ecosystem
modelled as a NetworkX DiGraph (Directed Graph).

GST PRIMER:
  GSTIN  = 15-char Goods & Services Tax Identification Number
  ITC    = Input Tax Credit (tax paid on purchases, claimable)
  GSTR-1 = Supplier's sales return (monthly/quarterly)
  GSTR-2B= Auto-populated buyer purchase register
  GSTR-3B= Buyer's summary return + ITC claim
  IRN    = Invoice Reference Number (e-invoice, 64-char SHA-256)
  EWB    = E-Way Bill (required for goods movement > ₹50,000)

Graph model:
  Nodes = 8 entity types (Taxpayer, GSTIN, Invoice, IRN, Return,
          EWayBill, TaxPayment, MismatchEvent)
  Edges = 9 relationship types (REGISTERED_AS, SUPPLIER_OF, ...)

Why graph?
  Multi-hop ITC validation requires traversal:
    Recipient GSTIN → Invoice → Supplier GSTIN → Return (GSTR-1)
    → GSTR-2B → GSTR-3B → TaxPayment
  SQL needs O(n²) JOINs per hop; graph traversal is O(k).
  Cycle detection (circular trading) is native to graph algorithms.
"""

from typing import TypedDict, Optional, List, Dict, Any
import networkx as nx


# ═══════════════════════════════════════════════════════════════
# NODE TYPE DEFINITIONS (TypedDict = typed schema contract)
# ═══════════════════════════════════════════════════════════════

class TaxpayerNode(TypedDict):
    """Legal entity registered under GST (company/individual)."""
    taxpayer_id:       str            # Internal unique ID
    name:              str            # Legal name as per PAN
    pan:               str            # 10-char Permanent Account Number
    registration_date: str            # ISO date YYYY-MM-DD
    category:          str            # Regular / Composition / SEZ / ISD
    sector:            str            # Manufacturing / Trading / Services / Export / E-commerce


class GSTINNode(TypedDict):
    """
    GST Identification Number node — one taxpayer can have multiple GSTINs
    (one per state where they operate).
    Format: SS XXXXXXXXXX Z C
      SS = state code (01-37)
      XXXXXXXXXX = 10-char PAN
      Z  = always 'Z'
      C  = checksum character
    """
    gstin:              str           # 15-char GSTIN
    state_code:         str           # 2-digit state code
    status:             str           # Active / Suspended / Cancelled
    registration_type:  str           # Regular / Composition / SEZ
    annual_turnover:    float         # INR
    filing_frequency:   str           # Monthly / Quarterly


class InvoiceNode(TypedDict):
    """
    Tax Invoice — the core document in GST ITC chain.
    B2B invoices above ₹5L require IRN (e-invoice mandate).
    IGST applies for inter-state; CGST+SGST for intra-state.
    """
    invoice_no:       str             # Seller's invoice number
    invoice_date:     str             # ISO date
    invoice_type:     str             # B2B / B2C / SEZ / EXP
    taxable_value:    float           # Pre-tax base amount (INR)
    cgst:             float           # Central GST (intra-state only)
    sgst:             float           # State GST (intra-state only)
    igst:             float           # Integrated GST (inter-state only)
    cess:             float           # Additional cess (luxury/sin goods)
    total_value:      float           # taxable_value + all taxes
    place_of_supply:  str             # 2-digit state code of delivery


class IRNNode(TypedDict):
    """
    Invoice Reference Number — cryptographic proof of e-invoice.
    Generated by IRP (Invoice Registration Portal) as SHA-256 hash of:
      SupplierGSTIN + DocType + DocNo + DocDate + RecipientGSTIN
    Mandatory for B2B invoices where supplier turnover > ₹5 Crore.
    """
    irn:        str                   # 64-char SHA-256 hex string
    ack_no:     str                   # 15-digit acknowledgement number
    ack_date:   str                   # ISO datetime
    status:     str                   # ACTIVE / CANCELLED


class ReturnNode(TypedDict):
    """
    GST Return filing — monthly/quarterly compliance document.
    GSTR-1:  Supplier files all outward supplies (sales)
    GSTR-2B: Auto-drafted from suppliers' GSTR-1 (read-only for buyer)
    GSTR-3B: Buyer files summary + claims ITC + pays net tax
    """
    return_period:    str             # MMYYYY e.g. "012024"
    return_type:      str             # GSTR1 / GSTR2B / GSTR3B
    filed_date:       Optional[str]   # None if not yet filed
    status:           str             # FILED / PENDING / LATE
    total_itc:        float           # ITC claimed/available (INR)
    total_liability:  float           # Tax liability (INR)


class EWayBillNode(TypedDict):
    """
    E-Way Bill — mandatory electronic permit for goods movement.
    Required when consignment value > ₹50,000.
    Generated on EWB portal before movement begins.
    """
    ewb_no:             str           # 12-digit EWB number
    ewb_date:           str           # Generation date
    valid_till:         str           # Expiry date (distance-based)
    mode_of_transport:  str           # ROAD / RAIL / AIR / SHIP
    vehicle_no:         str           # Vehicle/transport ID
    distance:           int           # Distance in km


class TaxPaymentNode(TypedDict):
    """
    Tax Payment Challan — proof of GST deposit to government.
    A GSTIN's ITC claim is only valid if their supplier has
    deposited the collected tax (Section 16(2)(c) CGST Act).
    """
    challan_no:     str               # Challan identification number
    payment_date:   str               # ISO date
    igst_paid:      float             # IGST component paid
    cgst_paid:      float             # CGST component paid
    sgst_paid:      float             # SGST component paid
    mode:           str               # ONLINE / OFFLINE


class MismatchEventNode(TypedDict):
    """
    Reconciliation mismatch — a discrepancy between GSTR-1 and GSTR-2B.
    Each mismatch puts ITC at risk of disallowance under Section 16.
    """
    mismatch_id:       str            # Unique mismatch reference
    mismatch_type:     str            # See MismatchTaxonomy keys
    detected_date:     str            # When the mismatch was found
    amount_at_risk:    float          # ITC at risk (INR)
    risk_level:        str            # CRITICAL / HIGH / MEDIUM / LOW
    root_cause:        str            # Explanation of why mismatch occurred
    resolution_status: str            # PENDING / IN_PROGRESS / RESOLVED


# ═══════════════════════════════════════════════════════════════
# EDGE TYPE DEFINITIONS
# ═══════════════════════════════════════════════════════════════

EDGE_SCHEMA: Dict[str, Dict[str, Any]] = {
    "REGISTERED_AS": {
        "source":      "Taxpayer",
        "target":      "GSTIN",
        "properties":  [],
        "description": "A taxpayer registers as one or more GSTINs (one per state)",
        "cardinality": "1:N",
    },
    "SUPPLIER_OF": {
        "source":      "GSTIN",
        "target":      "Invoice",
        "properties":  ["supply_type"],   # INTER_STATE / INTRA_STATE / SEZ
        "description": "Supplier GSTIN issued this invoice",
        "cardinality": "1:N",
    },
    "RECIPIENT_OF": {
        "source":      "Invoice",
        "target":      "GSTIN",
        "properties":  ["itc_eligible"],  # True/False
        "description": "This GSTIN is the buyer/recipient of the invoice",
        "cardinality": "N:1",
    },
    "HAS_IRN": {
        "source":      "Invoice",
        "target":      "IRN",
        "properties":  [],
        "description": "Invoice has an e-invoice reference number",
        "cardinality": "1:1",
    },
    "REPORTED_IN": {
        "source":      "Invoice",
        "target":      "Return",
        "properties":  ["table_no"],      # GSTR-1 table B2B/B2CL etc.
        "description": "Invoice reported in a GST return filing",
        "cardinality": "N:M",
    },
    "COVERED_BY": {
        "source":      "Invoice",
        "target":      "EWayBill",
        "properties":  [],
        "description": "Goods shipment covered by this E-Way Bill",
        "cardinality": "N:1",
    },
    "PAID_VIA": {
        "source":      "Return",
        "target":      "TaxPayment",
        "properties":  [],
        "description": "Tax liability in this return paid via this challan",
        "cardinality": "N:1",
    },
    "HAS_MISMATCH": {
        "source":      "Invoice",
        "target":      "MismatchEvent",
        "properties":  [],
        "description": "This invoice has a reconciliation mismatch",
        "cardinality": "1:N",
    },
    "TRANSACTS_WITH": {
        "source":      "GSTIN",
        "target":      "GSTIN",
        "properties":  ["transaction_count", "total_value", "risk_flag"],
        "description": "Business relationship between two GSTINs (supply chain link)",
        "cardinality": "N:M",
        "note":        "Circular patterns in this relationship indicate potential fraud",
    },
}


# ═══════════════════════════════════════════════════════════════
# MISMATCH TAXONOMY
# 7 mismatch types covering all ITC reconciliation failure modes
# ═══════════════════════════════════════════════════════════════

MISMATCH_TAXONOMY: Dict[str, Dict[str, Any]] = {
    "AMOUNT_MISMATCH": {
        "subtypes":         ["TAXABLE_VALUE_DIFF", "TAX_AMOUNT_DIFF", "TOTAL_VALUE_DIFF", "CESS_DIFF"],
        "risk_level":       "HIGH",
        "itc_impact":       True,
        "itc_risk_multiplier": 1.0,
        "description":      (
            "Invoice taxable value or tax amount in supplier's GSTR-1 differs from "
            "buyer's GSTR-2B. Common cause: supplier filed amendment (GSTR-1A) without "
            "notifying buyer. ITC claimable only up to the GSTR-2B amount."
        ),
        "legal_reference":  "Section 16(2)(c) CGST Act + Rule 36(4) CGST Rules",
        "resolution":       "Vendor amendment in GSTR-1A; buyer adjusts ITC in next period",
    },
    "INVOICE_MISSING_2B": {
        "subtypes":         ["GSTR1_NOT_FILED", "INVOICE_NOT_UPLOADED", "LATE_FILING"],
        "risk_level":       "HIGH",
        "itc_impact":       True,
        "itc_risk_multiplier": 1.2,
        "description":      (
            "Invoice present in buyer's Purchase Register but absent from GSTR-2B. "
            "Most common cause: supplier did not file GSTR-1 for the period. "
            "Section 16(2)(aa) CGST Act (w.e.f. 01-Jan-2022): ITC can only be claimed "
            "if invoice appears in GSTR-2B."
        ),
        "legal_reference":  "Section 16(2)(aa) CGST Act 2017 (Amendment 2022)",
        "resolution":       "Follow up with supplier to file GSTR-1; defer ITC until 2B updated",
    },
    "EXTRA_IN_2B": {
        "subtypes":         ["DUPLICATE_INVOICE", "WRONG_RECIPIENT", "CANCELLED_NOT_REMOVED"],
        "risk_level":       "MEDIUM",
        "itc_impact":       False,
        "itc_risk_multiplier": 0.5,
        "description":      (
            "Invoice appears in GSTR-2B but not in buyer's Purchase Register. "
            "Could indicate duplicate upload by supplier or invoice meant for another GSTIN. "
            "No ITC impact directly, but indicates record-keeping gaps."
        ),
        "legal_reference":  "Rule 36(1) CGST Rules — ITC documentary requirements",
        "resolution":       "Supplier to cancel duplicate entry; buyer to flag in GSTR-3B",
    },
    "GSTIN_MISMATCH": {
        "subtypes":         ["WRONG_BUYER_GSTIN", "WRONG_SELLER_GSTIN", "SUSPENDED_GSTIN"],
        "risk_level":       "HIGH",
        "itc_impact":       True,
        "itc_risk_multiplier": 1.3,
        "description":      (
            "Supplier's GSTIN on invoice differs from GSTR-2B, or buyer's GSTIN "
            "is incorrect. Frequently caused by incorrect GSTIN at point of purchase. "
            "ITC is denied as invoice cannot be linked to correct taxpayer."
        ),
        "legal_reference":  "Section 16(1) CGST Act — registered taxable person requirement",
        "resolution":       "Rectify GSTIN at procurement stage; supplier to amend GSTR-1",
    },
    "DATE_MISMATCH": {
        "subtypes":         ["PERIOD_MISMATCH", "FILING_CUTOFF_BREACH", "BACKDATED_INVOICE"],
        "risk_level":       "MEDIUM",
        "itc_impact":       True,
        "itc_risk_multiplier": 0.8,
        "description":      (
            "Invoice date falls in a different return period than what was reported. "
            "GSTR-1 filed in November showing an October invoice not matched in "
            "October GSTR-2B. ITC must be claimed in the correct period."
        ),
        "legal_reference":  "Section 16(4) CGST Act — time limit for ITC claim",
        "resolution":       "Reclassify invoice to correct period; amend GSTR-3B if required",
    },
    "IRN_MISMATCH": {
        "subtypes":         ["IRN_NOT_GENERATED", "IRN_CANCELLED", "IRN_TAMPERED", "FAKE_IRN"],
        "risk_level":       "CRITICAL",
        "itc_impact":       True,
        "itc_risk_multiplier": 1.5,   # Highest multiplier — potential fraud
        "description":      (
            "Invoice Reference Number (e-invoice) is invalid, cancelled, or tampered. "
            "IRN is a cryptographic proof of invoice authenticity from IRP. "
            "Invalid IRN = invoice may be fabricated. CRITICAL risk — potential fraud."
        ),
        "legal_reference":  "Rule 48(4) CGST Rules + Section 122(1)(ii) — fraudulent ITC",
        "resolution":       "Immediate ITC reversal; report to GSTN; potential DGGI referral",
    },
    "EWAYBILL_MISSING": {
        "subtypes":         ["EWB_NOT_GENERATED", "EWB_EXPIRED", "DISTANCE_MISMATCH"],
        "risk_level":       "MEDIUM",
        "itc_impact":       False,
        "itc_risk_multiplier": 0.6,
        "description":      (
            "Goods movement above ₹50,000 without valid E-Way Bill. "
            "While EWB non-compliance does not directly disallow ITC, it creates "
            "an audit trail gap and may indicate invoice fabrication for non-physical goods."
        ),
        "legal_reference":  "Rule 138 CGST Rules — E-Way Bill mandate",
        "resolution":       "Generate EWB retroactively if possible; document transit records",
    },
}


# ═══════════════════════════════════════════════════════════════
# SCHEMA REGISTRY — for graph builders to reference
# ═══════════════════════════════════════════════════════════════

NODE_TYPES = {
    "Taxpayer":      TaxpayerNode,
    "GSTIN":         GSTINNode,
    "Invoice":       InvoiceNode,
    "IRN":           IRNNode,
    "Return":        ReturnNode,
    "EWayBill":      EWayBillNode,
    "TaxPayment":    TaxPaymentNode,
    "MismatchEvent": MismatchEventNode,
}

SCHEMA_VERSION = "1.0.0"
SCHEMA_DESCRIPTION = "GST Knowledge Graph Schema — India's GST ITC Reconciliation Engine"


def create_empty_graph() -> nx.DiGraph:
    """
    Create a new empty directed graph with schema metadata.
    Nodes should be added using: G.add_node(node_id, type=..., **properties)
    Edges should be added using: G.add_edge(u, v, type=..., **properties)
    """
    G = nx.DiGraph()
    G.graph["schema_version"]   = SCHEMA_VERSION
    G.graph["schema_description"] = SCHEMA_DESCRIPTION
    G.graph["node_types"]        = list(NODE_TYPES.keys())
    G.graph["edge_types"]        = list(EDGE_SCHEMA.keys())
    return G


def validate_node(node_type: str, properties: dict) -> list[str]:
    """Return list of missing required fields for a node type."""
    schema_class = NODE_TYPES.get(node_type)
    if not schema_class:
        return [f"Unknown node type: {node_type}"]
    required = list(schema_class.__annotations__.keys())
    missing = [f for f in required
               if f not in properties and
               not str(schema_class.__annotations__[f]).startswith("typing.Optional")]
    return missing


# ═══════════════════════════════════════════════════════════════
# DEMO — run this file to see schema summary
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 60)
    print("  GraphLedger AI — GST Knowledge Graph Schema v1.0")
    print("=" * 60)

    G = create_empty_graph()

    print(f"\n📦 NODE TYPES ({len(NODE_TYPES)}):")
    for name, cls in NODE_TYPES.items():
        fields = list(cls.__annotations__.keys())
        print(f"  {name:<20} {len(fields)} fields: {', '.join(fields[:4])}{'...' if len(fields) > 4 else ''}")

    print(f"\n🔗 EDGE TYPES ({len(EDGE_SCHEMA)}):")
    for name, meta in EDGE_SCHEMA.items():
        props = meta["properties"] or ["none"]
        print(f"  {name:<25} {meta['source']:<15} → {meta['target']:<15}  props: {props}")

    print(f"\n⚠️  MISMATCH TAXONOMY ({len(MISMATCH_TAXONOMY)} types):")
    for mtype, info in MISMATCH_TAXONOMY.items():
        impact = "ITC at risk" if info["itc_impact"] else "No ITC impact"
        print(f"  {mtype:<25} Risk: {info['risk_level']:<8} | {impact} "
              f"| Multiplier: {info['itc_risk_multiplier']}x")

    print(f"\n📊 GRAPH CAPACITY:")
    print(f"  Node types:         {len(NODE_TYPES)}")
    print(f"  Edge types:         {len(EDGE_SCHEMA)}")
    print(f"  Mismatch categories:{len(MISMATCH_TAXONOMY)}")
    total_fields = sum(len(cls.__annotations__) for cls in NODE_TYPES.values())
    print(f"  Total schema fields:{total_fields}")
    print(f"  Schema version:     {SCHEMA_VERSION}")
    print(f"\n✅ Schema loaded successfully into empty NetworkX DiGraph")
